### ISSUE TITLE
how to compile on ubuntu 14.04?

### ISSUE THREAD

**Issue by timotheecour** [jubatus/jubatus-msgpack-rpc#24]
I'm struggling trying to compile this library (or any msgpack-rpc library for C++ for that matter). Please advise.

```
sudo apt-get install libmsgpack-dev
cd ~/git_clone
git clone https://github.com/jubatus/jubatus-msgpack-rpc
./bootstrap
./configure
#--with-mpio=DIR option may be needed.
```

Then:

```
cd ~/git_clone
git clone https://github.com/jubatus/jubatus-mpio
./bootstrap
./configure
make -j8
make install DESTDIR=$HOME
libtool --finish $HOME/usr/local/lib
#doesn' seem to build libmpio.a so I also did:
ln -s $HOME/usr/local/lib/libjubatus_mpio.a $HOME/usr/local/lib/libmpio.a

#trying again:
cd ~/msgpack-rpc-cpp
./configure --with-mpio=$HOME/usr/local

types.h:22:23: fatal error: mp/memory.h: No such file or directory
```

**Comment by kmaehashi** [comment]
You cannot build msgpack-rpc-cpp against jubatus-mpio.  The allowed combinations are:

* https://github.com/jubatus/jubatus-msgpack-rpc and https://github.com/jubatus/jubatus-mpio

or 

* https://github.com/msgpack-rpc/msgpack-rpc-cpp and https://github.com/frsyuki/mpio

The installation path of ``jubatus_mpio`` library needs to be specified as ``--with-mpio`` argument when configuring jubatus-msgpack-rpc.

**Comment by timotheecour** [comment]
```
cd ~/git_clone/jubatus-msgpack-rpc/cpp
./configure --with-jubatus-mpio=$HOME/usr/local
make
````

```
In file included from exception.h:23:0,
                 from session.h:24,
                 from client.h:23,
                 from client.cc:18:
future.h: In member function 'void msgpack::rpc::future::type<void>::get()':
future.h:99:17: error: 'nil' is not a member of 'msgpack::v2::type'
   { future::get<msgpack::type::nil>(); }
                 ^
future.h:99:17: note: suggested alternative:
In file included from /home/timothee/.linuxbrew/include/msgpack/adaptor/nil_decl.hpp:13:0,
                 from /home/timothee/.linuxbrew/include/msgpack/adaptor/nil.hpp:13,
                 from /home/timothee/.linuxbrew/include/msgpack/type.hpp:13,
                 from /home/timothee/.linuxbrew/include/msgpack.hpp:18,
                 from types.h:22,
                 from client.h:22,
                 from client.cc:18:
/home/timothee/.linuxbrew/include/msgpack/v1/adaptor/nil_decl.hpp:28:15: note:   'msgpack::v1::type::nil'
 typedef nil_t nil;
               ^
```

**Comment by kmaehashi** [comment]
If you're using MessagePack v1.0+, try msgpack-1.x branch:

https://github.com/jubatus/jubatus-msgpack-rpc/tree/msgpack-1.x

**Comment by timotheecour** [comment]
```
cd /home/timothee/git_clone/jubatus-msgpack-rpc/cpp
git fetch
git checkout msgpack-1.x
./bootstrap
./configure --with-jubatus-mpio=$HOME/usr/local
make clean
make
```

future.h: In member function 'void msgpack::rpc::future::type<void>::get()':
future.h:99:17: error: 'nil' is not a member of 'msgpack::v2::type'
   { future::get<msgpack::type::nil>(); }

**Comment by timotheecour** [comment]
also tried:
```
brew install msgpack
./configure --with-jubatus-mpio=$HOME/usr/local --with-msgpack=/home/timothee/.linuxbrew/
```

**Comment by timotheecour** [comment]
+ @redboltz please advise!

**Comment by timotheecour** [comment]
this works as a temporary workaround, but uses old versions:

```
cd $git_clone_D/msgpack-c
git checkout cpp-1.4
./bootstrap
./configure
make
make install DESTDIR=$HOME/temp/stage3

cd $git_clone_D/jubatus-msgpack-rpc/cpp
git checkout msgpack-1.x
./configure --with-jubatus-mpio=$HOME/temp/stage3/usr/local --with-msgpack=$HOME/temp/stage3/usr/local/
make
make install DESTDIR=$HOME/temp/stage3
```

However, I'm running into trouble when trying to run examples:
```
#include <jubatus/msgpack/rpc/client.h>
```
crashes (will open another bug)

```
In file included from /home/timothee/temp/stage3/usr/local/include/jubatus/msgpack/rpc/session.h:23:0,                                                                                                             from /home/timothee/temp/stage3/usr/local/include/jubatus/msgpack/rpc/client.h:23,                                                                                                                from /home/timothee/git_clone//lhrep//tests/test_msgpack_rpc.cpp:8:                                                                                                              /home/timothee/temp/stage3/usr/local/include/jubatus/msgpack/rpc/protocol.h:61:28: error: 'tuple_type' in namespace 'msgpack::v1::type' does not name a template type                                 typename msgpack::type::tuple_type<Parameter>::transparent_reference param,                                                                                                                                               ^
```
